\author[1,2]{Cameron Dart}
\author[2]{The Big Dog}
\affil[1]{National Center For Supercomputing Applications (NCSA)}
\affil[2]{Laboratory for Computation, Data, and Machine Learning}
\affil[3]{Illinois Data Science Initiative}
\title{LaTeX Template For an iDSI Technical Report}

\newcommand{\makecoverpage}{
	\begin{titlepage}
	\center 
	\textsc{\LARGE Illinois Data Science Initiative} \\
	[1.5cm]\textsc{\Large Technical Reports} \HRule \\ 
	[0.4cm]{\huge \bfseries }\\
	\HRule \\
	[1.5cm]\Large \emph{Author: }Cameron Dart \\
	[3cm]{\large \today} % Date
	%\includegraphics{Logo}\\[1cm] % uncomment if you want to place a logo
	\vfill
	\end{titlepage}
}